
//Array
//find max, min, secon max second min in array
//reverse array-Reverse an array without reverse()
//Remove duplicates from an array
//Find the second largest number
//Merge two arrays and remove duplicates
//Count occurrences of each element
//Flatten a nested array (1-level deep)
//move zeros to end
//Find pairs whose sum equals target - twosum

//String
//Reverse a string (without built-ins)
//Check if a string is a palindrome
//Count vowels and consonants
//Remove duplicate characters 
//Check if two strings are anagram
//First non-repeating character
//snake_case → camelCase(Capitalize all words except first.)
//Capitalize first letter of each word
//Count number of words

